using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ChampionsOfForest.Network
{
	public partial class Commands
	{
		public enum CommandType
		{
			NETWORK_STAT_UPDATE,
			DIFFICULTY_INFO_REQUEST,
			DIFFICULTY_INFO_ANSWER,
			SPELL_BLACK_HOLE,
			SPELL_SANCTUARY,
			SPELL_SUNFLARE,
			SPELL_BLACKFLAME,
			SPELL_WARCRY,
			SPELL_PORTAL,
			SPELL_MAGIC_ARROW,
			SPELL_PURGE,
			SPELL_CATACLYSM,
			SPELL_BALLLIGHTNING,
			SPELL_BALLLIGHTNING_REQUEST,
			SPELL_BALL_LIGHTNING_TRIGGER,
			SPELL_PARRY,
			SPELL_FART,
			SPELL_TAUNT,
			SPELL_BASH_HIT_ENEMY,
			ITEM_REMOVE_PICKUP,
			ITEM_SPAWN_PICKUP,
			ENEMY_STATS_INFO_BROADCAST,
			ENEMY_STATS_INFO_RECEIVE,
			SPELL_ENEMY_BLIZZARD,
			SPELL_ENEMY_RADIANCE,
			SPELL_ENEMY_CHAINS,
			SPELL_ENEMY_CHAINS_VISUAL,
			SPELL_ENEMY_TRAP_SPHERE,
			SPELL_ENEMY_LASAER,
			SPELL_ENEMY_METEOR,
			BUFF_GIVE_PLAYER,
			STUN_PLAYER,
			EXPERIENCE_KILL,
			EXPERIENCE_FINAL,
			PLAYER_STATS_INFO_REQUEST,
			PLAYER_STATS_INFO_RECEIVE,
			HITMARKER_COLOR,
			ENEMY_DEBUFF_SLOW,
			ENEMY_DEBUFF_FIRE,
			ENEMY_DEBUFF_DOT,
			ENEMY_DEBUFF_DAMAGE_TAKEN,
			ENEMY_KNOCKBACK,
			ENEMY_STATS_UPDATE_VOLATILE_REQUEST,
			ENEMY_STATS_UPDATE_VOLATILE_ANSWER,
			ITEM_PICKUP_PLAYER_COLLECTED,
			ITEM_ADD_TO_INVENTORY,
			EQUIP_CUSTOM_WEAPON,
			ENEMY_SYNC_APPEARANCE_REQUEST,
			ENEMY_SYNC_APPEARANCE,
			PING_CLEAR,
			PING_PLACE,
			PING_ENEMY_INFO,
			SPELL_BALLLIGHTNING_CLIENT_VISUAL,
			ITEM_ARCHANGEL_FF,
			BUFF_ADD,
			BUFF_ADD_AOE,
			BUFF_ADD_GLOBAL,
		}
	}
}
