using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ChampionsOfForest.System
{
	internal static class ResourceList
	{
		internal static void FillResources()
		{
			new Resource(1, "wheel.png");
			new Resource(2, "wheelOn.png");
			new Resource(5, "SpellBG.png");
			new Resource(6, "SpellFrame.png");
			new Resource(8, "CoolDownFill.png");
			new Resource(12, "Item1SlotBg.png");
			new Resource(13, "Item1Frame.png");
			new Resource(15, "ProgressBack.png");
			new Resource(16, "ProgressFill.png");
			new Resource(17, "ProgressFront.png");
			new Resource(18, "CombatTimer.png");
			new Resource(20, "BlackHoleTex.png");
			new Resource(21, "BlackHole.obj");
			new Resource(22, "Leaf.png");
			new Resource(24, "SmallCircle.png");
			new Resource(25, "Row.png");
			new Resource(26, "snowflake.png");
			new Resource(27, "Background.png");
			new Resource(28, "HorizontalListItem.png");
			new Resource(30, "Space.png");
			new Resource(40, "amulet.obj");
			new Resource(41, "Glove.obj");
			new Resource(42, "ChestArmor.obj");
			new Resource(43, "ring.obj");
			new Resource(44, "Boots2.obj");
			new Resource(45, "Bracer.obj");
			//new Resource(46, "Boots1.obj");
			//new Resource(47, "Boots2.obj");
			new Resource(48, "helmet_armet_2.obj");
			new Resource(49, "Shield.obj");
			new Resource(50, "Pants2.obj");
			new Resource(51, "Sword.obj");
			new Resource(52, "HeavySword.obj");
			new Resource(53, "Shoulder.obj");
			//new Resource(59, "SwordMetalic.png");
			new Resource(60, "SwordTexture.png");
			new Resource(61, "SwordColor.png");
			new Resource(62, "SwordEmissive.png");
			new Resource(64, "SwordNormal.png");
			new Resource(65, "SwordRoughness.png");
			new Resource(66, "SwordAmbientOcculusion.png");
			new Resource(67, "ManyParticles.png");
			new Resource(68, "InverseSphere.obj");
			new Resource(69, "ChainPart.obj");
			new Resource(70, "Spike.obj");
			new Resource(71, "particle.png");
			new Resource(72, "Melee.jpg");
			new Resource(73, "Magic.jpg");
			new Resource(74, "Ranged.jpg");
			new Resource(75, "Defensive.jpg");
			new Resource(76, "Utility.jpg");
			new Resource(77, "Support.jpg");
			new Resource(78, "Background1.jpg");
			new Resource(82, "PerkNode1.png");
			new Resource(81, "PerkNode2.png");
			new Resource(83, "PerkNode3.png");
			new Resource(84, "PerkNode4.png");
			new Resource(85, "ItemBoots.png");
			new Resource(86, "ItemGloves.png");
			new Resource(87, "ItemPants.png");
			new Resource(88, "ItemGreatSword.png");
			new Resource(89, "ItemLongSword.png");
			new Resource(90, "ItemRing.png");
			new Resource(91, "ItemHelmet.png");
			new Resource(92, "ItemBoots1.png");
			new Resource(93, "ItemBracer.png");
			new Resource(94, "ItemBracer2.png");
			new Resource(95, "ItemShoulder.png");
			new Resource(96, "ItemChest.png");
			new Resource(98, "ItemQuiver.png");
			new Resource(99, "ItemShield.png");
			new Resource(100, "ItemScarf.png");
			new Resource(101, "ItemAmulet.png");
			new Resource(102, "Heart.obj");
			new Resource(103, "HeartTexture.png");
			new Resource(104, "HeartNormal.png");
			new Resource(105, "ItemHeart.png");
			new Resource(106, "Corner.png");
			new Resource(107, "BeamParticleHorizontal.png");
			new Resource(108, "Hammer.obj");
			new Resource(109, "ItemHammer.png");
			new Resource(110, "ItemScroll.png");
			new Resource(111, "FlameParticle.png");
			new Resource(112, "Portal.obj");
			new Resource(113, "FantasyArrow.obj");
			new Resource(114, "SpellPortal.png");
			new Resource(115, "SpellDarkFlame.png");
			new Resource(116, "Quiver.obj");
			new Resource(117, "SpellReach.png");
			new Resource(118, "SpellShield.png");
			new Resource(119, "BlackHoleSpell.png");
			new Resource(120, "FlareSpell.png");
			new Resource(121, "BlinkSpell.png");
			new Resource(122, "SpellHealDome.png");
			new Resource(123, "WarCrySpell.png");
			new Resource(124, "Scroll.obj");
			new Resource(125, "SpellMagicArrow.png");
			new Resource(126, "SpellEffect.png");
			new Resource(127, "MultishotSpell.png");
			new Resource(128, "Iceparticle.png");
			new Resource(129, "Shockwave.png");
			new Resource(130, "ballLightningSpell.png");
			new Resource(131, "SpellBerserk.png");
			new Resource(132, "SpellPurge.png");
			new Resource(133, "SpellGold.png");
			new Resource(134, "Bash.png");
			new Resource(135, "SeekingArrow.png");
			new Resource(136, "Frenzy.png");
			new Resource(137, "Focus.png");
			new Resource(138, "ItemAxe.png");
			new Resource(139, "Parry.wav");
			new Resource(140, "Parry.png");
			new Resource(141, "Cataclysm.png");
			new Resource(142, "MassacreBG.png");
			new Resource(143, "BuffBG.png");
			new Resource(144, "BuffBorder.png");
			new Resource(145, "BuffActive.png");
			new Resource(146, "ArmorBuff.png");
			new Resource(147, "Armordebuff.png");
			new Resource(148, "AtkSlow.png");
			new Resource(149, "AtkSpeedBuff.png");
			new Resource(150, "BuffMS.png");
			new Resource(151, "DamageBuff.png");
			new Resource(152, "Damagedebuff.png");
			new Resource(153, "Deathpact.png");
			new Resource(154, "DebuffImmune.png");
			new Resource(155, "DebuffResistant.png");
			new Resource(156, "DebuffSlowMs.png");
			new Resource(157, "poisoned.png");
			new Resource(158, "RootImmune.png");
			new Resource(159, "SecondChanceCD.png");
			new Resource(160, "StaminaRegen.png");
			new Resource(161, "StaminaRegenDebuff.png");
			new Resource(162, "rooted.png");
			new Resource(163, "Stun.png");
			new Resource(164, "LevelUp.png");
			new Resource(165, "BloodInfusedArrow.png");
			new Resource(167, "Bow.obj");
			new Resource(168, "BowNormals.png");
			new Resource(169, "FireBowTex.png");
			new Resource(170, "ItemFireBow.png");
			new Resource(171, "EnemyPingElite.png");
			new Resource(172, "EnemyPingNormal.png");
			new Resource(173, "LocationPing.png");
			new Resource(174, "PickupPing.png");
			new Resource(175, "Polearm.obj");
			new Resource(181, "itemPolearm.png");
			new Resource(182, "FartSpell.png");
			new Resource(184, "ItemOre.png");
			new Resource(185, "ItemFeather.png");
			new Resource(186, "ItemSharkTooth.png");
			new Resource(187, "ItemSapphire.png");
			new Resource(188, "ItemMoonstone.png");
			new Resource(189, "SpellTaunt.png");
			new Resource(190, "ItemSocketDrill.png");
			new Resource(191, "BottleBlue.png");
			new Resource(192, "BottleGreen.png");
			new Resource(193, "BottleOrange.png");
			new Resource(194, "BottleOrange2.png");
			new Resource(195, "BottleYellow.png");
			new Resource(196, "BottleCrimson.png");
			new Resource(197, "BottleGray.png");
			new Resource(198, "BottleAcid.png");
			new Resource(199, "BottlePurple.png");
			new Resource(200, "SpellSnowstorm.png");
			new Resource(201, "SpellFirebolt.png");
			//Sound files
			new Resource(1000, "thundersound.wav");
			new Resource(1001, "Levelup.wav");
			new Resource(1002, "ClickUp.wav");
			new Resource(1003, "ClickDown.wav");
			new Resource(1004, "Drop.wav");
			new Resource(1005, "MeteorImpact.wav");
			new Resource(1006, "MeteorSFX.wav");
			new Resource(1007, "Purge.wav");
			new Resource(1008, "Unlock.wav");
			new Resource(1009, "BloodInfusedArrow.wav");
			new Resource(1010, "Warp.wav");
			new Resource(1011, "SpellUnlock.wav");
			new Resource(1012, "Pickup.wav");
			new Resource(1013, "sacrificeSfx.wav");
			new Resource(1014, "SnapFreeze.wav");
			new Resource(1015, "Blizzard.wav");
			new Resource(1016, "BlackholeDisappearing.wav");
			new Resource(1017, "Roaring Cheeks spell sfx.wav");

			new Resource(1050, "flip1.wav");
			new Resource(1051, "flip.wav");
			new Resource(1052, "flipanvl.wav");
			new Resource(1053, "flipaxe.wav");
			new Resource(1054, "flipblst.wav");
			new Resource(1055, "flipbody.wav");
			new Resource(1056, "flipbook.wav");
			new Resource(1057, "flipbow.wav");
			new Resource(1058, "flipcap.wav");
			new Resource(1059, "flipharm.wav");
			new Resource(1060, "fliplarm.wav");
			new Resource(1061, "flipmag.wav");
			new Resource(1062, "flipmag1.wav");
			new Resource(1063, "flippot.wav");
			new Resource(1064, "flipring.wav");
			new Resource(1065, "fliprock.wav");
			new Resource(1066, "flipsarc.wav");
			new Resource(1067, "flipscrl.wav");
			new Resource(1068, "flipshld.wav");
			new Resource(1069, "flipsign.wav");
			new Resource(1070, "invanvl.wav");
			new Resource(1071, "invaxe.wav");
			new Resource(1072, "invblst.wav");
			new Resource(1073, "invbody.wav");
			new Resource(1074, "invbook.wav");
			new Resource(1075, "invbow.wav");
			new Resource(1076, "invcap.wav");
			new Resource(1077, "invgrab.wav");
			new Resource(1078, "invharm.wav");
			new Resource(1079, "invlarm.wav");
			new Resource(1080, "invpot.wav");
			new Resource(1081, "invring.wav");
			new Resource(1082, "invrock.wav");
			new Resource(1083, "invscrol.wav");
			new Resource(1084, "invshiel.wav");
			new Resource(1085, "invsign.wav");
			new Resource(1086, "invstaf.wav");
			new Resource(1087, "invsword.wav");

			//Asset Bundles
			new Resource(2000, "balllightning", Resource.ResourceType.AssetBundle);
			new Resource(2001, "axe", Resource.ResourceType.AssetBundle);
			new Resource(2002, "deathmark", Resource.ResourceType.AssetBundle);
			new Resource(2003, "fire", Resource.ResourceType.AssetBundle);
			new Resource(2004, "blackholeeffect.bruh", Resource.ResourceType.AssetBundle);
			new Resource(2005, "update157", Resource.ResourceType.AssetBundle);
		} 
	}
}
